### ISSUE TITLE
make plugin compatible with  idea 211 (ie 2021.1)

### ISSUE THREAD

**Issue by vgramer** [open-policy-agent/opa-idea-plugin#100]
# Description
The last version of Idea is 2021.1 and the plugin is only compatible until 2020.3.  So we need to make it compatible with the new version

- [ ] run plugin verifier against version 211
- [ ] update github action  to generate 211 version

**Comment by rLitto** [comment]
Any news on this?

**Comment by vgramer** [comment]
plugin has been push to Jetbrains marketplace, should be available in few days
