### ISSUE TITLE
Compatibility with Intellij 2021.3

### ISSUE THREAD

**Issue by adam-sandor** [open-policy-agent/opa-idea-plugin#118]
Intellij 2021.3 update screen is telling me that the OPA plugin wont be compatible with this version.

**Comment by anderseknert** [comment]
Seems like the plugin now got disabled :( Any progress on this @vgramer?

**Comment by vgramer** [comment]
@anderseknert I opened PR yesterday, it took me more time thatn expecting because idea was resolving depencies in loop. i thought it was because of my changes but in fact it was not ...

**Comment by anderseknert** [comment]
@vgramer gotcha! Yeah, considering the size of the PR I definitely understand it took a while :)

**Comment by Harmelodic** [comment]
From 3 hours ago, @vgramer put on that PR:
> i will make a release this afternoon or tomorrow afternoon

So for those, like me, who are looking at this issue being Closed, but it's still not working in IntelliJ - the update is coming, we just have to wait.

**Comment by vgramer** [comment]
the plugin has been released and is under review in the JetBrains marketplace. It should be available soon.

In the meantime you can install it from disk:
1. download the plugin from the GitHub release:
    * choose `opa-idea-plugin-v0.7.0-211.zip` for ide version 2021.1
    * choose `opa-idea-plugin-v0.7.0-211.zip` for ide version >= 2021.2
2.  go to `Settings / Preferences / Plugins` , choose `install plugin from disk` and select the zip of the plugin

**Comment by Harmelodic** [comment]
It's [public](https://plugins.jetbrains.com/plugin/14865-open-policy-agent/versions/stable/149482).
