### ISSUE TITLE
OPA 不支持 goland  Version: 2022.1

### ISSUE THREAD

**Issue by doaspx** [open-policy-agent/opa-idea-plugin#128]
OPA does not support Golan version: 2022.1

<img width="574" alt="image" src="https://user-images.githubusercontent.com/4754495/163741608-5be2ac57-9070-41b3-9497-c5525cc5bb08.png">

How to solve this problem？

**Comment by doaspx** [comment]
GoLand 2022.1
Build #GO-221.5080.224, built on April 14, 2022

**Comment by vgramer** [comment]
Hi 

the new version of the plugin has been released and is under review by the JetBrains team. It should be available in the marketplace in the next few days. In the meantime, you can still  install the plugin manually by downloading it from the [Github release](https://github.com/open-policy-agent/opa-idea-plugin/releases/tag/v0.8.0)
