### ISSUE TITLE
Add support for IntelliJ IDEA 2022.3

### ISSUE THREAD

**Issue by haakobja** [open-policy-agent/opa-idea-plugin#137]
# What would you like to be added
Support for IntellJ IDEA 2022.3

# Why is this needed
It would be nice to be able to use this plugin in IntellIJ IDEA 2022.3

# Implementation details

**Comment by hermitmaster** [comment]
@vgramer any idea when we can expect to see a release that supports Jetbrains 2022.3?

**Comment by vgramer** [comment]
very soon :)

**Comment by lorthirk** [comment]
+1 for the 2022.3 support!
