### ISSUE TITLE
Add support for IntelliJ IDEA 2023.1

### ISSUE THREAD

**Issue by SilverSilence** [open-policy-agent/opa-idea-plugin#143]
# What would you like to be added
Support for IntellJ IDEA 2023.1
# Why is this needed
It would be nice to be able to use this plugin in IntellIJ IDEA 2023.1
# Implementation details

**Comment by SilverSilence** [comment]
If it's not too much to ask, can I try to make a PR for this? I've never contributed to a project and would love to use this as an opportunity to do so. I would make another comment here if I don't know how.

**Comment by vgramer** [comment]
Sure, contributions are always welcome. I quickly review the release notes, and I think we only need to bump some dependencies... However, if you don't have experience in developing Idea plugins, it may not be the easiest or most interesting issue to start contributing.

**Comment by SilverSilence** [comment]
I don't know what I'm doing wrong to pass that DCO check.. 😅
And it's fine if it's not the most interesting, I'm just happy to have the chance to contribute anything at all :)

**Comment by anderseknert** [comment]
Thanks for stepping up, @SilverSilence 👍

**Comment by 0x9090** [comment]
Can we go ahead and get these updates merged? Seems like a minor change, that just needs to be shipped
