### ISSUE TITLE
Plugin not compatible with latest version of Jetbrains IDEs (2023.2)

### ISSUE THREAD

**Issue by nslusher-sf** [open-policy-agent/opa-idea-plugin#152]
# What would you like to be added
Support for the latest version of Jetbrains IDEs

# Why is this needed
The plugin does not work on the latest version of the IDE (in my case GoLand 2023.2)

# Implementation details

**Comment by hermitmaster** [comment]
Same here. GoLand 2023.2 as well.

**Comment by samarthya-gupta1** [comment]
It says the latest plugin requires "Plugin 'Open Policy Agent' (version 'v0.10.0') is not compatible with the current version of the IDE, because it requires build 231.* or older but the current build is IC-232.8660.185".

**Comment by anderseknert** [comment]
@vgramer let me know if I can support you in this in any way 😃
