### ISSUE TITLE
Does not support latest IntelliJ

### ISSUE THREAD

**Issue by FredrikAugust** [open-policy-agent/opa-idea-plugin#167]
# Actual Behavior

It does not support IntelliJ IDEA 2023.3 (Ultimate Edition).

# Expected  Behavior

It should support the latest IntelliJ version.

# Environment
 - OS: macOS Sonoma 14.3
 - IDE full name and version: IntelliJ IDEA 2023.3 (Ultimate Edition)

**Comment by anderseknert** [comment]
See https://github.com/open-policy-agent/opa-idea-plugin/pull/166#issuecomment-1929115281

**Comment by anderseknert** [comment]
I don't blame you. Scanning closed PR's for clues isn't ideal, but hopefully we won't need to for long :)

**Comment by anderseknert** [comment]
Done, AFAICS
