### ISSUE TITLE
Please update plugin to support IntelliJ IDEA 2024.2 and later

### ISSUE THREAD

**Issue by rorybakerfmr** [open-policy-agent/opa-idea-plugin#174]
# Actual Behavior
Plugin is automatically disabled by IntelliJ: "Incompatible: requires IDE build 241.* or earlier"

# Expected  Behavior
The plugin should be updated to support IDEA 2024.2

Note that starting with 2024.2, the new UI is the default, and the classic UI is being supported as an optional plugin for another year. Please see https://blog.jetbrains.com/blog/2024/07/08/the-new-ui-becomes-the-default-in-2024-2/ for details

# Environment
 - OS: Linux
```
Linux -redacted- 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID: Ubuntu
Description:    Ubuntu 24.04 LTS
Release:        24.04
Codename:       noble
```
IntelliJ IDEA Community Edition installed through Snap Store

 - OPA version: N/A

 - IDE full name and version: IntelliJ IDEA 2024.2.0.1 (Community Edition)
```
Build #IC-242.20224.387, built on August 13, 2024
Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
```

 - plugin version: v0.12.0

**Comment by vgramer** [comment]
fixed by #173 . plugin is under review and should be available in next few days
