### ISSUE TITLE
Make plugin run on 2024.3

### ISSUE THREAD

**Issue by musk** [open-policy-agent/opa-idea-plugin#179]
# What would you like to be added
I would like to have this plugin installable for 2024.3

# Why is this needed
Plugin is disabled because it is only allowed to run up to build 242.* but new IntellliJ is 243.*

# Implementation details

Should just be changing untilBuild=243.* 
but I haven't tested if it is still compatible and does not crash.

**Comment by vgramer** [comment]
Im working on it. This time there is more work to do ...
