### ISSUE TITLE
Grammar: else clause cannot have empty query

### ISSUE THREAD

**Issue by seanburke-wf** [open-policy-agent/opa-idea-plugin#84]
# Actual Behavior
Due to the construction of a `rule` in the plugin's grammar, any `else` _must_ be followed by `"{" query "}"`, otherwise a syntax error is reported.

# Expected Behavior
`else` with simple unification is allowed.

# How To Reproduce

Create a file with the following contents:
```
package com.foo

foo = true {
    input.x < input.y
} else = false
```

Observe that there is a syntax error "<infix operator> or '{' expected" at the end of input.

Run `opa check` on the file and observe that there are no errors.

# Environment
 - OS:  macOS 10.14

 - OPA version:  0.25.2

 - IDE full name and version:  GoLand 2020.3.1

 - plugin version:  0.4.0.0-202

# Additional context

**Comment by vgramer** [comment]
thank you for reporting the issue
