### ISSUE TITLE
Escaped quote in string is wrongfully treated as syntax error

### ISSUE THREAD

**Issue by artis3n** [open-policy-agent/opa-idea-plugin#97]
# Actual Behavior

![image](https://user-images.githubusercontent.com/6969296/112513763-0af86480-8d6b-11eb-975f-6674d0785059.png)

# Expected  Behavior

```rego
imageInArg := trim(argNameAndValue[1], "\"")
```

is the correct syntax for trimming quotes `"` from a string so that should not throw a syntax error.

# How To Reproduce
1.  Observe this is correct syntax - <https://play.openpolicyagent.org/p/jV6Hpr3Sk0>
2. Copy that rego code and place into `.rego` file in Intellij with this plugin active
3. Observe that a syntax error is wrongfully highlighted on the line

# Environment
 - OS: OSX 10.15.7

 - OPA version: 0.27.1

 - IDE full name and version: Intellij IDEA Ultimate 2020.3

 - plugin version: 0.5.0.SNAPSHOT-202

# Additional context

**Comment by anderseknert** [comment]
Good catch! You probably know already, but you could work around this by using backticks until fixed.

`imageInArg := trim(argNameAndValue[1], `"`)`

**Comment by artis3n** [comment]
I did not realize that, I just left the highlight hang :)
Thanks!

**Comment by vgramer** [comment]
@artis3n  thank you for reporting the bug. 

I quickly look at it. It's a regression introduced by #67
